version: 2.1
# Include Kubernetes orb definition
orbs:
  kubernetes: circleci/kubernetes@2.0.0 # Use a specific, stable version like @1.2.0 or @2.0.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true clean package
      - persist_to_workspace:
          root: ./
          paths:
            - target/
      - setup_remote_docker #version: 19.03.13

      - run:
          name: Render deployment.yaml using envsubst
          command: |
            envsubst < argo/deployment.yaml > argo/deployment.yaml
            
      - run:
          name: Configure Git User
          command: |
            git config user.email "circleci@example.com" # Use a dedicated email for CI commits
            git config user.name "CircleCI Bot"
            git add argo/deployment.yaml
            git commit -m "Update deployment [skip ci]" || echo "No changes"
            git push origin main
            
      # build and push Docker image
      - run: 
          name: build and push Docker image
          command: |
            TAG=3.0
            docker build -t $DOCKERHUB_USERNAME/gitops-foundations:$TAG --build-arg JAR_FILE=*.jar .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/gitops-foundations:$TAG
            echo "export IMAGE_TAG=$TAG" >> $BASH_ENV # Make tag available to subsequent jobs    
            
  deploy:
    docker:
      - image: cimg/base:current # A base image with Git and common tools like `sed`
    steps:
      - checkout
      
      - run:
          name: Load Image Tag from Build Job
          command: |
            source $BASH_ENV # Load the IMAGE_TAG exported from the build job
            echo "Image tag for deployment: $IMAGE_TAG"
            K8S_MANIFEST_PATH="argo/deployment.yaml" 

      - run:
          name: Commit and Push Changes to Git
          command: |
            git add "$K8S_MANIFEST_PATH"
            git commit -m "CircleCI: Deploy gitops-foundations with image $IMAGE_TAG [skip ci]" # [skip ci] prevents infinite loop
            # Use the GIT_TOKEN environment variable for authentication
            git push "https://$GIT_USERNAME:$GIT_TOKEN@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git" HEAD:main # Adjust to your repo and branch

workflows:
  main:
    jobs:
      - build:
          context: DockerHub
      - deploy:
          requires:
            - build # Ensure deploy runs only after build is successful
          context: # Add contexts needed for Git push and CircleCI Project ID
            - DockerHub # If DOCKERHUB_USERNAME/PASSWORD are needed here (unlikely for deploy job)
            - GitOps # A new context for GIT_USERNAME, GIT_TOKEN, CIRCLECI_PROJECT_ID
